{
  "contract": "0x173bddd4f27a7737a86b2918d816018701329013",
  "tool": "mythril",
  "start": 1563645647.6132953,
  "end": 1563646007.0247126,
  "duration": 359.41141724586487,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 3890,
        "debug": "calldata_kkICOTest77_32 + 4: 0xc290137095b13347e55005a6dc184559e0489f1233480050d0fb4bba17d34179\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_kkICOTest77_4: 0x9c9efb7ae5acd378025256a3945f5859076e809243093d9ecae2636c9fd28979\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xc290137095b13347e55005a6dc184559e0489f1233480050d0fb4bba17d34179\ncalldata_kkICOTest77_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_kkICOTest77: 0x4\ncallvalue: 0x0\n",
        "description": "A possible integer overflow exists in the function `transfer(address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
        "filename": "/unique_chucks/27/0x173bddd4f27a7737a86b2918d816018701329013.sol",
        "function": "transfer(address,uint256)",
        "lineno": 156,
        "title": "Integer Overflow ",
        "type": "Warning"
      },
      {
        "address": 3903,
        "debug": "The exception is triggered under the following conditions:\n\ncalldata_kkICOTest77_32 + 4: 0x6218000d800000000000000000000000039800002005500633e06f771baff7fc\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_kkICOTest77_4: 0xbd5dfeabad0efffffffffeffffffffffd599ffefbfe6f24271e80e64322c0700\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x6218000d800000000000000000000000039800002005500633e06f771baff7fc\ncalldata_kkICOTest77_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_kkICOTest77: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/27/0x173bddd4f27a7737a86b2918d816018701329013.sol",
        "function": "transfer(address,uint256)",
        "lineno": 156,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 3927,
        "code": "assert(c >= a)",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\ncalldata_kkICOTest77_32 + 4: 0x1\ncalldata_kkICOTest77_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_kkICOTest77: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/27/0x173bddd4f27a7737a86b2918d816018701329013.sol",
        "function": "transfer(address,uint256)",
        "lineno": 148,
        "title": "Exception state",
        "type": "Informational"
      }
    ],
    "success": true
  }
}