{"error": null, "issues": [{"address": 226, "code": "allet] < amount) {re", "debug": "storage_4: 0xc21b0287c025689fdbdcb6e36cdc4fd0e7a7891bcf511569038576410e5fb7e4\ncallvalue: 0x5c814fd7d44da193921182d7d01ecd18a017cdc3ec5d47e0011e041110de260a\ncalldata_ValkyrieNetwork_0: 0xd700000000000000000000000000000000000000000000000000000000\ncalldatasize_ValkyrieNetwork: 0x4\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/47/0x17cd1bf1f528ac6dea7877b0d68bee5e6cb0fe27.sol", "function": "fallback", "lineno": 97, "title": "Integer Overflow ", "type": "Warning"}, {"address": 616, "code": "send(msg.value);\n    }\n  }", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x81d080a98b21acd1f67e42ed3f4f7865c9b691bf0fc77bdff7b56ae9574cffa1\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\nUDiv(storage_5,_256): 0xf18ab4ca2b85309c1ab1afad3f6dff97c037933fa897529dc7c7627653682021\nstorage_3: 0x1\ncallvalue: 0xf18ab4ca2b85309c1ab1afad3f6dff97c037933fa897529dc7c7627653682021\ncalldata_ValkyrieNetwork_0: 0x8d00000000000000000000000000000000000000000000000000000000\ncalldatasize_ValkyrieNetwork: 0x4\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/47/0x17cd1bf1f528ac6dea7877b0d68bee5e6cb0fe27.sol", "function": "fallback", "lineno": 101, "title": "Integer Overflow ", "type": "Warning"}, {"address": 900, "debug": "", "description": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.", "filename": "/unique_chucks/47/0x17cd1bf1f528ac6dea7877b0d68bee5e6cb0fe27.sol", "function": "fallback", "lineno": 103, "title": "Unchecked CALL return value", "type": "Informational"}, {"address": 5594, "code": "c >= ", "debug": "calldata_ValkyrieNetwork_32 + 4: 0x57f25cd000000000000000000000000000000000000000000000000000000000\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_ValkyrieNetwork_4: 0xa8795cd3fffffffffffffffffffffffffffffffffffffffffffffffffffffffe\ncalldata_ValkyrieNetwork_0: 0xd73dd62300000000000000000000000000000000000000000000000000000000\ncalldatasize_ValkyrieNetwork: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `increaseApproval(address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/47/0x17cd1bf1f528ac6dea7877b0d68bee5e6cb0fe27.sol", "function": "increaseApproval(address,uint256)", "lineno": 14, "title": "Integer Overflow ", "type": "Warning"}, {"address": 5607, "code": ");return c;\n  ", "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_ValkyrieNetwork_4: 0x1\ncalldata_ValkyrieNetwork_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_ValkyrieNetwork_0: 0xd73dd62300000000000000000000000000000000000000000000000000000000\ncalldatasize_ValkyrieNetwork: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/47/0x17cd1bf1f528ac6dea7877b0d68bee5e6cb0fe27.sol", "function": "increaseApproval(address,uint256)", "lineno": 14, "title": "Exception state", "type": "Informational"}], "success": true}