{
  "contract": "0x8935ad1b34a620526bab4d637d8cd7601a0ac1bd",
  "tool": "mythril",
  "start": 1563741347.4363718,
  "end": 1563741369.1449,
  "duration": 21.70852828025818,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 7325,
        "code": " }\n\n  /**\n  * ",
        "debug": "The exception is triggered under the following conditions:\n\ncalldata_TongramToken_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_1: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_TongramToken_0: 0x42966c6800000000000000000000000000000000000000000000000000000000\ncalldatasize_TongramToken: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/43/0x8935ad1b34a620526bab4d637d8cd7601a0ac1bd.sol",
        "function": "burn(uint256)",
        "lineno": 38,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 7343,
        "code": "}\n}\n\n",
        "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_TongramToken_32_+_4: 0xc050fffff320c00020003d81af848540000000000000040000110001bd062022\ncalldata_TongramToken_32 + 36: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_TongramToken_4: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\ncalldata_TongramToken_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_TongramToken_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_TongramToken: 0x4\ncallvalue: 0x0\n",
        "description": "A possible integer overflow exists in the function `transferFrom(address,address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
        "filename": "/unique_chucks/43/0x8935ad1b34a620526bab4d637d8cd7601a0ac1bd.sol",
        "function": "transferFrom(address,address,uint256)",
        "lineno": 47,
        "title": "Integer Overflow ",
        "type": "Warning"
      },
      {
        "address": 7356,
        "code": "@title Ownable",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_TongramToken_4: 0x1\ncalldata_TongramToken_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_TongramToken_0: 0xd73dd62300000000000000000000000000000000000000000000000000000000\ncalldatasize_TongramToken: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/43/0x8935ad1b34a620526bab4d637d8cd7601a0ac1bd.sol",
        "function": "increaseApproval(address,uint256)",
        "lineno": 51,
        "title": "Exception state",
        "type": "Informational"
      }
    ],
    "success": true
  }
}