{"error": null, "issues": [{"address": 572, "code": " }\n        if (", "debug": "callvalue: 0x9dc0c5f8040000\nstorage_0: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc\nblock_number: 0x0\ncaller: 0x0\nstorage_87903029871075914254377627908054574944891091886930582284385770809450030037083: 0x0\nstorage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_7: 0x0\ncalldatasize_Random: 0x3\nstorage_13: 0x0\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/21/0xad7e9b5b9d15f2b26464ecbe76065f033b126a6c.sol", "function": "fallback", "lineno": 67, "title": "Integer Overflow ", "type": "Warning"}, {"address": 5210, "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_calldata_Random_32_+_4: 0x0\nstorage_3: 0x0\ncalldata_Random_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_Random: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/21/0xad7e9b5b9d15f2b26464ecbe76065f033b126a6c.sol", "function": "transfer(address,uint256)", "lineno": 319, "title": "Exception state", "type": "Informational"}, {"address": 6191, "code": " fee_balance += ", "debug": "callvalue: 0x27872000000000\nblock_number: 0x0\nretval_3119: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_0: 0x1\ncaller: 0x0\nstorage_87903029871075914254377627908054574944891091886930582284385770809450030037083: 0x0\nstorage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_7: 0x0\ncalldatasize_Random: 0x3\nstorage_13: 0x0\n", "description": "A possible integer underflow exists in the function `fallback`.\nThe subtraction may result in a value < 0.", "filename": "/unique_chucks/21/0xad7e9b5b9d15f2b26464ecbe76065f033b126a6c.sol", "function": "fallback", "lineno": 170, "title": "Integer Underflow", "type": "Warning"}, {"address": 6204, "code": "\n    }\n    \n    /// sending rewards", "debug": "storage_5: 0xffffffffffffffffffffffffffffffffffffdffffffffeffffffffffffffffff\ncallvalue: 0x2786f300000000\nblock_number: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nretval_3119: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_0: 0x1\ncaller: 0x0\nstorage_87903029871075914254377627908054574944891091886930582284385770809450030037083: 0x0\nstorage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_7: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldatasize_Random: 0x3\nstorage_13: 0x0\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/21/0xad7e9b5b9d15f2b26464ecbe76065f033b126a6c.sol", "function": "fallback", "lineno": 170, "title": "Integer Overflow ", "type": "Warning"}, {"address": 6307, "code": " > 0);\n        uint val =", "debug": "callvalue: 0x27872000000000\nblock_number: 0x0\nbalance_at_1461501637330902918203684832716283019655932542975 & 0: 0x27871fffffffff\nretval_3119: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_0: 0x1\ncaller: 0x0\nstorage_87903029871075914254377627908054574944891091886930582284385770809450030037083: 0x0\nstorage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_7: 0x0\ncalldatasize_Random: 0x3\nstorage_13: 0x0\n", "description": "A possible integer underflow exists in the function `fallback`.\nThe subtraction may result in a value < 0.", "filename": "/unique_chucks/21/0xad7e9b5b9d15f2b26464ecbe76065f033b126a6c.sol", "function": "fallback", "lineno": 175, "title": "Integer Underflow", "type": "Warning"}, {"address": 6315, "code": "uire(fee_balance > 0);\n        uint val = ", "debug": "storage_15: 0xc000000000000000000000000000000000000000000000000020067000400260\ncallvalue: 0x41c5eeefc0fc03\nbalance_at_1461501637330902918203684832716283019655932542975 & 0: 0x800000000000000000000000000000000000000000000000000000002fc00e27\nblock_number: 0x0\nretval_3119: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_0: 0x1\ncaller: 0x0\nstorage_87903029871075914254377627908054574944891091886930582284385770809450030037083: 0x0\nstorage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_7: 0x0\ncalldatasize_Random: 0x3\nstorage_13: 0x0\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/21/0xad7e9b5b9d15f2b26464ecbe76065f033b126a6c.sol", "function": "fallback", "lineno": 175, "title": "Integer Overflow ", "type": "Warning"}], "success": true}