2019-08-07 01:29:17,736: [12] m.main:INFO: Registered plugins: DetectUnusedRetVal, DetectReentrancySimple, DetectInvalid, DetectSuicidal, DetectReentrancyAdvanced, DetectUninitializedStorage, DetectEnvInstruction, DetectDelegatecall, DetectIntegerOverflow, DetectUninitializedMemory, DetectExternalCallAndLeak
2019-08-07 01:29:17,736: [12] m.main:INFO: Beginning analysis
2019-08-07 01:29:17,749: [12] m.e.manticore:INFO: Starting symbolic create contract
2019-08-07 01:29:40,703: [12] m.e.manticore:INFO: Starting symbolic transaction: 0
2019-08-07 01:30:27,239: [1031] m.e.detectors:WARNING: INVALID instruction
2019-08-07 01:30:55,245: [1040] m.e.detectors:WARNING: Potentially reading uninitialized storage
2019-08-07 01:37:21,990: [1039] m.c.worker:ERROR: Exception in state 5: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-07 01:42:20,335: [1040] m.e.detectors:WARNING: INVALID instruction