{"error": null, "issues": [{"address": 1241, "code": "l) onlyOwner canDistr public {\n         for (uint i = 0; i < addresses.length; i++) {\n\t     if (getEthBalance(addresses[i]) < _ethbal) {\n \t         continue;\n             }\n             balances[owner] -= _value;\n             balances[addresses[i]] += _value;\n             Transfer(owner, addresses[i], _value);\n         }\n    }\n    \n    function balanceOf(address _owner) constant public returns (uint256) {\n\t", "debug": "calldata_Veriseum_4: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc\ncalldata_Veriseum_0: 0xc7ed4d8c00000000000000000000000000000000000000000000000000000000\ncalldatasize_Veriseum: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `distributeVM(address[],uint256,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/25/0x29be8344f0e80be4ce9bcf6b1de233f57f2f1101.sol", "function": "distributeVM(address[],uint256,uint256)", "lineno": 74, "title": "Integer Overflow ", "type": "Warning"}, {"address": 2093, "code": "to, uint256 _amount) onlyPayloadSiz", "debug": "The exception is triggered under the following conditions:\n\ncalldatasize_Veriseum: 0x60\ncalldata_Veriseum_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/25/0x29be8344f0e80be4ce9bcf6b1de233f57f2f1101.sol", "function": "transferFrom(address,address,uint256)", "lineno": 95, "title": "Exception state", "type": "Informational"}, {"address": 2446, "code": "sg.sender] -= _amount;\n", "debug": "calldatasize_Veriseum: 0x800000000000000000000000000000000000000000000000000000000020\ncalldata_Veriseum_32 + 36: 0x5b51dac49284d052eede5596fe2ba53f779697e2114bc7bdc6e9f6dddfb2fca1\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_Veriseum_32_+_4: 0xc8ad1292fc16ef648490c9b6f6a7ad897261541bdd738f31940d869d9824c19a\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x5b51dac49284d052eede5596fe2ba53f779697e2114bc7bdc6e9f6dddfb2fca1\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_Veriseum_4: 0x5b51dac49284d052eede5596fe2ba53f779697e2114bc7bdc6e9f6dddfb2fca1\ncalldata_Veriseum_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `transferFrom(address,address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/25/0x29be8344f0e80be4ce9bcf6b1de233f57f2f1101.sol", "function": "transferFrom(address,address,uint256)", "lineno": 116, "title": "Integer Overflow ", "type": "Warning"}, {"address": 3238, "code": "to, uint256 _amount) onlyPayloadSiz", "debug": "The exception is triggered under the following conditions:\n\ncalldatasize_Veriseum: 0x4\ncalldata_Veriseum_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/25/0x29be8344f0e80be4ce9bcf6b1de233f57f2f1101.sol", "function": "transfer(address,uint256)", "lineno": 95, "title": "Exception state", "type": "Informational"}, {"address": 3455, "code": "    balances[_to] += _a", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_Veriseum_4: 0x23d8a8520f724073445afe4bb9673704f5f700b5059efe000e50c6dfebb67db9\ncalldatasize_Veriseum: 0x800000000000000000000000000000000000000000000000000050\ncalldata_Veriseum_32 + 4: 0xef9dac035840d3446cf7e308735b46f504077e95d5dcc1feef6ce61e0ba5f9a9\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xef9dac035840d3446cf7e308735b46f504077e95d5dcc1feef6ce61e0ba5f9a9\ncalldata_Veriseum_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `transfer(address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/25/0x29be8344f0e80be4ce9bcf6b1de233f57f2f1101.sol", "function": "transfer(address,uint256)", "lineno": 101, "title": "Integer Overflow ", "type": "Warning"}, {"address": 4041, "code": "         Transfer(owner, ", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\nUDiv(storage_1,_256): 0x0\nbalance_at_1461501637330902918203684832716283019655932542975 &\ncalldata_Veriseum_cpy: 0x0\ncalldata_Veriseum_32 + 4: 0x1\ncalldata_Veriseum_32 + 36: 0x0\ncalldata_Veriseum_4 + calldata_Veriseum_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_5: 0x0\nstorage_1: 0x0\ncaller: 0x0\ncalldata_Veriseum_0: 0xc7ed4d8c00000000000000000000000000000000000000000000000000000000\ncalldatasize_Veriseum: 0x4\ncallvalue: 0x0\n", "description": "A possible integer underflow exists in the function `distributeVM(address[],uint256,uint256)`.\nThe subtraction may result in a value < 0.", "filename": "/unique_chucks/25/0x29be8344f0e80be4ce9bcf6b1de233f57f2f1101.sol", "function": "distributeVM(address[],uint256,uint256)", "lineno": 81, "title": "Integer Underflow", "type": "Warning"}, {"address": 4719, "debug": "", "description": "This contract executes a message call to an address provided as a function argument. Generally, it is not recommended to call user-supplied addresses using Solidity's call() construct. Note that attackers might leverage reentrancy attacks to exploit race conditions or manipulate this contract's state.", "filename": "/unique_chucks/25/0x29be8344f0e80be4ce9bcf6b1de233f57f2f1101.sol", "function": "withdrawForeignTokens(address)", "lineno": 153, "title": "Message call to external contract", "type": "Warning"}, {"address": 4719, "debug": "", "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 4977\n", "filename": "/unique_chucks/25/0x29be8344f0e80be4ce9bcf6b1de233f57f2f1101.sol", "function": "withdrawForeignTokens(address)", "lineno": 153, "title": "Multiple Calls", "type": "Information"}, {"address": 4977, "debug": "", "description": "This contract executes a message call to an address provided as a function argument. Generally, it is not recommended to call user-supplied addresses using Solidity's call() construct. Note that attackers might leverage reentrancy attacks to exploit race conditions or manipulate this contract's state.", "filename": "/unique_chucks/25/0x29be8344f0e80be4ce9bcf6b1de233f57f2f1101.sol", "function": "withdrawForeignTokens(address)", "lineno": 153, "title": "Message call to external contract", "type": "Warning"}], "success": true}