{
  "contract": "0x89234fab776fb68ec3c33529aa66f09b69a7b5f0",
  "tool": "mythril",
  "start": 1563656311.975474,
  "end": 1563656395.3187625,
  "duration": 83.34328842163086,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 1892,
        "code": "s >= ac.minimum",
        "debug": "",
        "description": "This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 134,
        "title": "Message call to external contract",
        "type": "Informational"
      },
      {
        "address": 1892,
        "code": "s >= ac.minimum",
        "debug": "",
        "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 2477\nCall at address: 2312\nCall at address: 2141\nCall at address: 2312\nCall at address: 2141\n",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 134,
        "title": "Multiple Calls",
        "type": "Information"
      },
      {
        "address": 1892,
        "code": "s >= ac.minimum",
        "debug": "",
        "description": "A possible transaction order independence vulnerability exists in function fallback. The value or direction of the call statement is determined from a tainted storage location",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 134,
        "title": "Transaction order dependence",
        "type": "Warning"
      },
      {
        "address": 2141,
        "code": "s));//!!!token ",
        "debug": "",
        "description": "This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 135,
        "title": "Message call to external contract",
        "type": "Informational"
      },
      {
        "address": 2141,
        "code": "s));//!!!token ",
        "debug": "",
        "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 2312\n",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 135,
        "title": "Multiple Calls",
        "type": "Information"
      },
      {
        "address": 2141,
        "code": "s));//!!!token ",
        "debug": "",
        "description": "A possible transaction order independence vulnerability exists in function fallback. The value or direction of the call statement is determined from a tainted storage location",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 135,
        "title": "Transaction order dependence",
        "type": "Warning"
      },
      {
        "address": 2312,
        "code": "y, msg.value,",
        "debug": "",
        "description": "This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 137,
        "title": "Message call to external contract",
        "type": "Informational"
      },
      {
        "address": 2312,
        "code": "y, msg.value,",
        "debug": "",
        "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 2477\n",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 137,
        "title": "Multiple Calls",
        "type": "Information"
      },
      {
        "address": 2312,
        "code": "y, msg.value,",
        "debug": "",
        "description": "A possible transaction order independence vulnerability exists in function fallback. The value or direction of the call statement is determined from a tainted storage location",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 137,
        "title": "Transaction order dependence",
        "type": "Warning"
      },
      {
        "address": 2477,
        "code": "it TokenPurchase(msg.se",
        "debug": "",
        "description": "This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 137,
        "title": "Message call to external contract",
        "type": "Informational"
      },
      {
        "address": 2477,
        "code": "it TokenPurchase(msg.se",
        "debug": "",
        "description": "A possible transaction order independence vulnerability exists in function fallback. The value or direction of the call statement is determined from a tainted storage location",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 137,
        "title": "Transaction order dependence",
        "type": "Warning"
      },
      {
        "address": 4929,
        "code": "/////////////////////////////////\n    //Create ne",
        "debug": "",
        "description": "This contract executes a message call to an address provided as a function argument. Generally, it is not recommended to call user-supplied addresses using Solidity's call() construct. Note that attackers might leverage reentrancy attacks to exploit race conditions or manipulate this contract's state.",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "setERC20address(address)",
        "lineno": 150,
        "title": "Message call to external contract",
        "type": "Warning"
      },
      {
        "address": 5061,
        "code": "unt\n    function newDeposit(Role _r",
        "debug": "",
        "description": "The contract account state is changed after an external call. Consider that the called contract could re-enter the function before this state change takes place. This can lead to business logic vulnerabilities.",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "setERC20address(address)",
        "lineno": 151,
        "title": "State change after external call",
        "type": "Warning"
      },
      {
        "address": 7879,
        "code": " a);\n",
        "debug": "storage_4: 0xa8795cd3fffffffffffffffffffffffffffffffffffffffffffffffffffffffe\ncallvalue: 0x57f25cd000000000000000000000000000000000000000000000000000000000\ncalldatasize_SynergisProxyDeposit: 0x3\n",
        "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 24,
        "title": "Integer Overflow ",
        "type": "Warning"
      },
      {
        "address": 7892,
        "code": "urn c;\n  }\n}\n\n",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_4: 0x1\ncallvalue: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_SynergisProxyDeposit_0: 0x22761f00000000000000000000000000000000000000000000000000000000\ncalldatasize_SynergisProxyDeposit: 0x4\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/25/0x89234fab776fb68ec3c33529aa66f09b69a7b5f0.sol",
        "function": "fallback",
        "lineno": 25,
        "title": "Exception state",
        "type": "Informational"
      }
    ],
    "success": true
  }
}