INFO:root:Contract /unique_chucks/2/0x12b306fa98f4cbb8d4457fdff3a0a0a56f07ccdf.sol:Controlled:
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 99.4%
INFO:symExec:	  Arithmetic bugs: 	 False
INFO:symExec:	  └> Overflow bugs: 	 False
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 0.282051086426 seconds ---
INFO:symExec:	====== Analysis Completed ======
INFO:root:Contract /unique_chucks/2/0x12b306fa98f4cbb8d4457fdff3a0a0a56f07ccdf.sol:MiniMeToken:
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 31.5%
Traceback (most recent call last):
  File "osiris/osiris.py", line 319, in <module>
    main()
  File "osiris/osiris.py", line 302, in main
    analyze(processed_evm_file, disasm_file, SourceMap(cname, args.source))
  File "osiris/osiris.py", line 137, in analyze

  .oooooo.             o8o            o8o          
 d8P'  `Y8b            `"'            `"'          
888      888  .oooo.o oooo  oooo d8b oooo   .oooo.o
888      888 d88(  "8 `888  `888""8P `888  d88(  "8
888      888 `"Y88b.   888   888      888  `"Y88b. 
`88b    d88' o.  )88b  888   888      888  o.  )88b
 `Y8bood8P'  8""888P' o888o d888b    o888o 8""888P'



!!! SYMBOLIC EXECUTION TIMEOUT !!!
    symExec.main(disasm_file, args.source, source_map)
  File "/root/osiris/symExec.py", line 2924, in main
    detect_bugs()
  File "/root/osiris/symExec.py", line 2778, in detect_bugs
    validate_width_conversions()
  File "/root/osiris/symExec.py", line 2496, in validate_width_conversions
    if len(get_vars(arithmetic_error["instruction"].data_out[0])) == 1 and len(get_vars(width_conversion)) == 1:
  File "/root/osiris/z3/z3util.py", line 162, in get_vars
    rs = get_vars(f_,rs)
  File "/root/osiris/z3/z3util.py", line 162, in get_vars
    rs = get_vars(f_,rs)
  File "/root/osiris/z3/z3util.py", line 162, in get_vars
    rs = get_vars(f_,rs)
  File "/root/osiris/z3/z3util.py", line 162, in get_vars
    rs = get_vars(f_,rs)
  File "/root/osiris/z3/z3util.py", line 161, in get_vars
    for f_ in f.children():
  File "/root/osiris/z3/z3.py", line 935, in children
    return [self.arg(i) for i in range(self.num_args())]
  File "/root/osiris/z3/z3.py", line 922, in arg
    return _to_expr_ref(Z3_get_app_arg(self.ctx_ref(), self.as_ast(), idx), self.ctx)
  File "/root/osiris/z3/z3.py", line 943, in _to_expr_ref
    k = Z3_get_ast_kind(ctx_ref, a)
  File "/root/osiris/z3/z3core.py", line 2582, in Z3_get_ast_kind
    _elems.Check(a0)
  File "/root/osiris/z3/z3core.py", line 1328, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: invalid argument